stages:
  - code-analysis
  - build-and-push
  - update-manifest

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  HOST_URL: 10.0.11.177

code-analysis:
  stage: code-analysis
  image: bellsoft/liberica-openjdk-alpine:17

  before_script:
    - apk add --no-cache curl unzip
    - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
    - unzip sonar-scanner.zip && mv sonar-scanner-* sonar-scanner
    - export PATH="$PWD/sonar-scanner/bin:$PATH"

  script:
    - echo "ğŸ” [SonarQube] ì •ì  ë¶„ì„ì„ ì‹œì‘í•©ë‹ˆë‹¤..."
    - |
      sonar-scanner \
        -Dsonar.projectKey=order-service \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://$HOST_URL:9000 \
        -Dsonar.token=$SONAR_TOKEN
    - echo "âœ… [SonarQube] ì •ì  ë¶„ì„ ì™„ë£Œ"

build-and-push:
  stage: build-and-push
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
  script:
    - echo "ğŸ”§ Docker ì´ë¯¸ì§€ ë¹Œë“œ ì¤‘..."
    - docker build -t $AWS_ECR_REPO:$IMAGE_TAG .
    - echo "ğŸ” AWS ECR ë¡œê·¸ì¸ ì¤‘..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPO
    - echo "ğŸ“¤ ECRì— ì´ë¯¸ì§€ í‘¸ì‹œ ì¤‘..."
    - docker push $AWS_ECR_REPO:$IMAGE_TAG

update-manifest:
  stage: update-manifest
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache git openssh
    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI Bot"
  script:
    - echo "ğŸ“ manifest ë ˆí¬ í´ë¡  ë° ì´ë¯¸ì§€ íƒœê·¸ ìˆ˜ì • ì¤‘..."
    - git clone http://$CI_GITLAB_USERNAME:$CI_GITLAB_TOKEN@$HOST_URL/root/manifest.git
    - cd manifest/product-service
    - >
      sed -i "s|image:.*|image: ${AWS_ECR_REPO}:${IMAGE_TAG}|" deployment.yaml
    - git add deployment.yaml
    - |
      if git diff --cached --quiet; then
        echo "ğŸ” ë³€ê²½ì‚¬í•­ ì—†ìŒ - ì»¤ë°‹ ìƒëµ"
      else
        git commit -m "chore: update image to ${IMAGE_TAG}"
        git push origin main
      fi